version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306" # Mapper le port 3306 du conteneur à 3307 sur l'hôte
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
